# Generated by Django 5.1.3 on 2024-12-16 08:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 57, 86711, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 57, 86711, tzinfo=datetime.timezone.utc))),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 57, 86711, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('user_input', models.TextField()),
                ('assistant_output', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('input_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_language', to='base.language')),
                ('output_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_language', to='base.language')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
