# Generated by Django 5.1.3 on 2024-12-19 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='identitydetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='identitydetail',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='identitydetail',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='insuranceinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='insuranceinfo',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='insuranceinfo',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proficiencycertification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proficiencycertification',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='proficiencycertification',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
    ]
