# Generated by Django 5.1.3 on 2024-12-16 08:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Index_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('add', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('group', models.CharField(max_length=50)),
                ('title', models.CharField(default='title', max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('is_updated', models.BooleanField(default=False)),
                ('question', models.TextField(max_length=5000)),
                ('answer', models.TextField(max_length=30000)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('deleted_at', models.DateTimeField(default=datetime.datetime(2024, 12, 16, 8, 56, 44, 408643, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload_file/')),
                ('chunk_size', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('embedding_cost', models.FloatField(blank=True, default=0, null=True)),
                ('embedding_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('index_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.index_name')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
