# Generated by Django 5.1.3 on 2024-12-19 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='index_name',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='index_name',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='index_name',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='upload_content',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='upload_content',
            name='deleted_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='upload_content',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 4, 57, 8, 557196, tzinfo=datetime.timezone.utc)),
        ),
    ]
